# Importing Data

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import requests
from bs4 import BeautifulSoup

import re

In [4]:
data=pd.read_csv(r"C:\Users\NaveenNani\movies_up.csv")

In [5]:
data.head()

,Unnamed: 0,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross,Director
0,0,\n1.\nThe Godfather\n,1972)\n,175 min,A,9.2,"\nCrime, Drama","408,693",$435.11M,"\nA\n|\n175 min\n|\n\nCrime, Drama \n"
1,1,\n2.\nGoodfellas\n,1990)\n,145 min,A,8.7,"\nBiography, Crime, Drama","31,290",$13.56M,"\nA\n|\n145 min\n|\n\nBiography, Crime, Drama ..."
2,2,\n3.\nPulp Fiction\n,1994)\n,154 min,A,8.9,"\nCrime, Drama","788,510",$380.26M,"\nA\n|\n154 min\n|\n\nCrime, Drama \n"
3,3,\n4.\nThe Usual Suspects\n,1995)\n,106 min,A,8.5,"\nCrime, Drama, Mystery","179,202",$11.50M,"\nA\n|\n106 min\n|\n\nCrime, Drama, Mystery ..."
4,4,\n5.\nApocalypse Now\n,1979)\n,147 min,R,8.5,"\nDrama, Mystery, War","74,217",$8.62M,"\nR\n|\n147 min\n|\n\nDrama, Mystery, War ..."

In [6]:
data.tail()

,Unnamed: 0,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross,Director
595,595,\n596.\nRio Bravo\n,1959)\n,141 min,NaN,8.0,\nWestern,"63,013",$12.54M,\n141 min\n|\n\nWestern \n
596,596,\n597.\nKind Hearts and Coronets\n,1949)\n,106 min,U,8.0,"\nComedy, Crime","37,578",NaN,"\nU\n|\n106 min\n|\n\nComedy, Crime \n"
597,597,\n598.\nChoke\n,2008)\n,92 min,R,6.4,"\nComedy, Drama","32,753",$2.93M,"\nR\n|\n92 min\n|\n\nComedy, Drama \n"
598,598,\n599.\nThe Conjuring\n,2013)\n,112 min,A,7.5,"\nHorror, Mystery, Thriller","507,280",$137.40M,"\nA\n|\n112 min\n|\n\nHorror, Mystery, Thrille..."
599,599,\n600.\nBody Heat\n,1981)\n,113 min,18,7.4,"\nCrime, Drama, Romance","36,182",$24.06M,"\n18\n|\n113 min\n|\n\nCrime, Drama, Romance ..."

In [7]:
# Checking the data columns

data.columns

Index(['Unnamed: 0', 'Movie Name', 'Year', 'Run Time', 'Certificate', 'Rating',
       'Genre', 'Votes', 'Gross', 'Director'],
      dtype='object')

In [8]:
# Checking the data shape

data.shape

(600, 10)

In [9]:
# Describing dataset

data.describe

<bound method NDFrame.describe of      Unnamed: 0                          Movie Name     Year Run Time  \
0             0               \n1.\nThe Godfather\n  1972)\n  175 min
1             1                  \n2.\nGoodfellas\n  1990)\n  145 min
2             2                \n3.\nPulp Fiction\n  1994)\n  154 min
3             3          \n4.\nThe Usual Suspects\n  1995)\n  106 min
4             4              \n5.\nApocalypse Now\n  1979)\n  147 min
..          ...                                 ...      ...      ...
595         595                 \n596.\nRio Bravo\n  1959)\n  141 min
596         596  \n597.\nKind Hearts and Coronets\n  1949)\n  106 min
597         597                     \n598.\nChoke\n  2008)\n   92 min
598         598             \n599.\nThe Conjuring\n  2013)\n  112 min
599         599                 \n600.\nBody Heat\n  1981)\n  113 min

    Certificate  Rating                                    Genre    Votes  \
0             A     9.2               \nCrime, Drama              408,693
1             A     8.7    \nBiography, Crime, Drama               31,290
2             A     8.9               \nCrime, Drama              788,510
3             A     8.5      \nCrime, Drama, Mystery              179,202
4             R     8.5        \nDrama, Mystery, War               74,217
..          ...     ...                                      ...      ...
595         NaN     8.0                    \nWestern               63,013
596           U     8.0              \nComedy, Crime               37,578
597           R     6.4              \nComedy, Drama               32,753
598           A     7.5  \nHorror, Mystery, Thriller              507,280
599          18     7.4      \nCrime, Drama, Romance               36,182

        Gross                                           Director
0    $435.11M   \nA\n|\n175 min\n|\n\nCrime, Drama            \n
1     $13.56M  \nA\n|\n145 min\n|\n\nBiography, Crime, Drama ...
2    $380.26M   \nA\n|\n154 min\n|\n\nCrime, Drama            \n
3     $11.50M  \nA\n|\n106 min\n|\n\nCrime, Drama, Mystery   ...
4      $8.62M  \nR\n|\n147 min\n|\n\nDrama, Mystery, War     ...
..        ...                                                ...
595   $12.54M              \n141 min\n|\n\nWestern            \n
596       NaN  \nU\n|\n106 min\n|\n\nComedy, Crime            \n
597    $2.93M   \nR\n|\n92 min\n|\n\nComedy, Drama            \n
598  $137.40M  \nA\n|\n112 min\n|\n\nHorror, Mystery, Thrille...
599   $24.06M  \n18\n|\n113 min\n|\n\nCrime, Drama, Romance  ...

[600 rows x 10 columns]>

In [10]:
# Checking info of data set

data.info

<bound method DataFrame.info of      Unnamed: 0                          Movie Name     Year Run Time  \
0             0               \n1.\nThe Godfather\n  1972)\n  175 min
1             1                  \n2.\nGoodfellas\n  1990)\n  145 min
2             2                \n3.\nPulp Fiction\n  1994)\n  154 min
3             3          \n4.\nThe Usual Suspects\n  1995)\n  106 min
4             4              \n5.\nApocalypse Now\n  1979)\n  147 min
..          ...                                 ...      ...      ...
595         595                 \n596.\nRio Bravo\n  1959)\n  141 min
596         596  \n597.\nKind Hearts and Coronets\n  1949)\n  106 min
597         597                     \n598.\nChoke\n  2008)\n   92 min
598         598             \n599.\nThe Conjuring\n  2013)\n  112 min
599         599                 \n600.\nBody Heat\n  1981)\n  113 min

    Certificate  Rating                                    Genre    Votes  \
0             A     9.2               \nCrime, Drama              408,693
1             A     8.7    \nBiography, Crime, Drama               31,290
2             A     8.9               \nCrime, Drama              788,510
3             A     8.5      \nCrime, Drama, Mystery              179,202
4             R     8.5        \nDrama, Mystery, War               74,217
..          ...     ...                                      ...      ...
595         NaN     8.0                    \nWestern               63,013
596           U     8.0              \nComedy, Crime               37,578
597           R     6.4              \nComedy, Drama               32,753
598           A     7.5  \nHorror, Mystery, Thriller              507,280
599          18     7.4      \nCrime, Drama, Romance               36,182

        Gross                                           Director
0    $435.11M   \nA\n|\n175 min\n|\n\nCrime, Drama            \n
1     $13.56M  \nA\n|\n145 min\n|\n\nBiography, Crime, Drama ...
2    $380.26M   \nA\n|\n154 min\n|\n\nCrime, Drama            \n
3     $11.50M  \nA\n|\n106 min\n|\n\nCrime, Drama, Mystery   ...
4      $8.62M  \nR\n|\n147 min\n|\n\nDrama, Mystery, War     ...
..        ...                                                ...
595   $12.54M              \n141 min\n|\n\nWestern            \n
596       NaN  \nU\n|\n106 min\n|\n\nComedy, Crime            \n
597    $2.93M   \nR\n|\n92 min\n|\n\nComedy, Drama            \n
598  $137.40M  \nA\n|\n112 min\n|\n\nHorror, Mystery, Thrille...
599   $24.06M  \n18\n|\n113 min\n|\n\nCrime, Drama, Romance  ...

[600 rows x 10 columns]>

In [11]:
#Checking null values

data.isnull().sum()

Unnamed: 0      0
Movie Name      0
Year            0
Run Time        0
Certificate    32
Rating          0
Genre           0
Votes           0
Gross          30
Director        0
dtype: int64

# Data Cleaning

In [12]:
# Dropping null values

movies=data.dropna()
movies

,Unnamed: 0,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross,Director
0,0,\n1.\nThe Godfather\n,1972)\n,175 min,A,9.2,"\nCrime, Drama","408,693",$435.11M,"\nA\n|\n175 min\n|\n\nCrime, Drama \n"
1,1,\n2.\nGoodfellas\n,1990)\n,145 min,A,8.7,"\nBiography, Crime, Drama","31,290",$13.56M,"\nA\n|\n145 min\n|\n\nBiography, Crime, Drama ..."
2,2,\n3.\nPulp Fiction\n,1994)\n,154 min,A,8.9,"\nCrime, Drama","788,510",$380.26M,"\nA\n|\n154 min\n|\n\nCrime, Drama \n"
3,3,\n4.\nThe Usual Suspects\n,1995)\n,106 min,A,8.5,"\nCrime, Drama, Mystery","179,202",$11.50M,"\nA\n|\n106 min\n|\n\nCrime, Drama, Mystery ..."
4,4,\n5.\nApocalypse Now\n,1979)\n,147 min,R,8.5,"\nDrama, Mystery, War","74,217",$8.62M,"\nR\n|\n147 min\n|\n\nDrama, Mystery, War ..."
...,...,...,...,...,...,...,...,...,...,...
593,593,\n594.\nFerris Bueller's Day Off\n,1986)\n,103 min,U,7.8,\nComedy,"358,202",$70.14M,\nU\n|\n103 min\n|\n\nComedy \n
594,594,\n595.\nI Love You Phillip Morris\n,2009)\n,102 min,R,6.6,"\nBiography, Comedy, Crime","96,420",$2.04M,"\nR\n|\n102 min\n|\n\nBiography, Comedy, Crime..."
597,597,\n598.\nChoke\n,2008)\n,92 min,R,6.4,"\nComedy, Drama","32,753",$2.93M,"\nR\n|\n92 min\n|\n\nComedy, Drama \n"
598,598,\n599.\nThe Conjuring\n,2013)\n,112 min,A,7.5,"\nHorror, Mystery, Thriller","507,280",$137.40M,"\nA\n|\n112 min\n|\n\nHorror, Mystery, Thrille..."
599,599,\n600.\nBody Heat\n,1981)\n,113 min,18,7.4,"\nCrime, Drama, Romance","36,182",$24.06M,"\n18\n|\n113 min\n|\n\nCrime, Drama, Romance ..."

In [13]:
#Dropping columns

movie=movies.drop(['Unnamed: 0','Director'],axis=1)
movie

,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross
0,\n1.\nThe Godfather\n,1972)\n,175 min,A,9.2,"\nCrime, Drama","408,693",$435.11M
1,\n2.\nGoodfellas\n,1990)\n,145 min,A,8.7,"\nBiography, Crime, Drama","31,290",$13.56M
2,\n3.\nPulp Fiction\n,1994)\n,154 min,A,8.9,"\nCrime, Drama","788,510",$380.26M
3,\n4.\nThe Usual Suspects\n,1995)\n,106 min,A,8.5,"\nCrime, Drama, Mystery","179,202",$11.50M
4,\n5.\nApocalypse Now\n,1979)\n,147 min,R,8.5,"\nDrama, Mystery, War","74,217",$8.62M
...,...,...,...,...,...,...,...,...
593,\n594.\nFerris Bueller's Day Off\n,1986)\n,103 min,U,7.8,\nComedy,"358,202",$70.14M
594,\n595.\nI Love You Phillip Morris\n,2009)\n,102 min,R,6.6,"\nBiography, Comedy, Crime","96,420",$2.04M
597,\n598.\nChoke\n,2008)\n,92 min,R,6.4,"\nComedy, Drama","32,753",$2.93M
598,\n599.\nThe Conjuring\n,2013)\n,112 min,A,7.5,"\nHorror, Mystery, Thriller","507,280",$137.40M
599,\n600.\nBody Heat\n,1981)\n,113 min,18,7.4,"\nCrime, Drama, Romance","36,182",$24.06M

# Removing Special Characters

In [14]:
movie['Genre'] = movie['Genre'].apply(lambda x:x.replace('\n',''))

In [15]:
movie['Movie Name'] = movie['Movie Name'].apply(lambda x:x.replace('\n',''))

In [16]:
movie['Year'] = movie['Year'].apply(lambda x:x.replace('\n',''))

In [17]:
movie['Votes'] = movie['Votes'].apply(lambda x:x.replace(',',''))

In [18]:
movie['Year'] = movie['Year'].apply(lambda x:x.replace(')',''))

In [19]:
movie['Gross in M $'] = movie['Gross'].apply(lambda x:x.replace('$',''))

In [20]:
movie['Gross in M $'] = movie['Gross in M $'].apply(lambda x:x.replace('M',' '))

In [21]:
movie

,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross,Gross in M $
0,1.The Godfather,1972,175 min,A,9.2,"Crime, Drama",408693,$435.11M,435.11
1,2.Goodfellas,1990,145 min,A,8.7,"Biography, Crime, Drama",31290,$13.56M,13.56
2,3.Pulp Fiction,1994,154 min,A,8.9,"Crime, Drama",788510,$380.26M,380.26
3,4.The Usual Suspects,1995,106 min,A,8.5,"Crime, Drama, Mystery",179202,$11.50M,11.50
4,5.Apocalypse Now,1979,147 min,R,8.5,"Drama, Mystery, War",74217,$8.62M,8.62
...,...,...,...,...,...,...,...,...,...
593,594.Ferris Bueller's Day Off,1986,103 min,U,7.8,Comedy,358202,$70.14M,70.14
594,595.I Love You Phillip Morris,2009,102 min,R,6.6,"Biography, Comedy, Crime",96420,$2.04M,2.04
597,598.Choke,2008,92 min,R,6.4,"Comedy, Drama",32753,$2.93M,2.93
598,599.The Conjuring,2013,112 min,A,7.5,"Horror, Mystery, Thriller",507280,$137.40M,137.40
599,600.Body Heat,1981,113 min,18,7.4,"Crime, Drama, Romance",36182,$24.06M,24.06

# Removing Numbers from Movie name column

In [22]:
movie['Movie Name'][0]

'1.The Godfather'

In [23]:
movie['Movie Name'][0].replace('1.','')

'The Godfather'

In [24]:
p=re.compile(r"\.(.*)")

In [25]:
p.findall(movie['Movie Name'][0])

['The Godfather']

In [26]:
m=movie['Movie Name'].apply(lambda x:p.findall(x))

In [27]:
m=m.apply(lambda x:"".join(x))

In [28]:
movie['Movie Name']=m

In [29]:
movie

,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross,Gross in M $
0,The Godfather,1972,175 min,A,9.2,"Crime, Drama",408693,$435.11M,435.11
1,Goodfellas,1990,145 min,A,8.7,"Biography, Crime, Drama",31290,$13.56M,13.56
2,Pulp Fiction,1994,154 min,A,8.9,"Crime, Drama",788510,$380.26M,380.26
3,The Usual Suspects,1995,106 min,A,8.5,"Crime, Drama, Mystery",179202,$11.50M,11.50
4,Apocalypse Now,1979,147 min,R,8.5,"Drama, Mystery, War",74217,$8.62M,8.62
...,...,...,...,...,...,...,...,...,...
593,Ferris Bueller's Day Off,1986,103 min,U,7.8,Comedy,358202,$70.14M,70.14
594,I Love You Phillip Morris,2009,102 min,R,6.6,"Biography, Comedy, Crime",96420,$2.04M,2.04
597,Choke,2008,92 min,R,6.4,"Comedy, Drama",32753,$2.93M,2.93
598,The Conjuring,2013,112 min,A,7.5,"Horror, Mystery, Thriller",507280,$137.40M,137.40
599,Body Heat,1981,113 min,18,7.4,"Crime, Drama, Romance",36182,$24.06M,24.06

In [30]:
movie.drop(['Gross'],axis=1,inplace=True)
movie

,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross in M $
0,The Godfather,1972,175 min,A,9.2,"Crime, Drama",408693,435.11
1,Goodfellas,1990,145 min,A,8.7,"Biography, Crime, Drama",31290,13.56
2,Pulp Fiction,1994,154 min,A,8.9,"Crime, Drama",788510,380.26
3,The Usual Suspects,1995,106 min,A,8.5,"Crime, Drama, Mystery",179202,11.50
4,Apocalypse Now,1979,147 min,R,8.5,"Drama, Mystery, War",74217,8.62
...,...,...,...,...,...,...,...,...
593,Ferris Bueller's Day Off,1986,103 min,U,7.8,Comedy,358202,70.14
594,I Love You Phillip Morris,2009,102 min,R,6.6,"Biography, Comedy, Crime",96420,2.04
597,Choke,2008,92 min,R,6.4,"Comedy, Drama",32753,2.93
598,The Conjuring,2013,112 min,A,7.5,"Horror, Mystery, Thriller",507280,137.40
599,Body Heat,1981,113 min,18,7.4,"Crime, Drama, Romance",36182,24.06

# Removing duplicate values

In [31]:
duplicates=movie.drop_duplicates()
duplicates

,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross in M $
0,The Godfather,1972,175 min,A,9.2,"Crime, Drama",408693,435.11
1,Goodfellas,1990,145 min,A,8.7,"Biography, Crime, Drama",31290,13.56
2,Pulp Fiction,1994,154 min,A,8.9,"Crime, Drama",788510,380.26
3,The Usual Suspects,1995,106 min,A,8.5,"Crime, Drama, Mystery",179202,11.50
4,Apocalypse Now,1979,147 min,R,8.5,"Drama, Mystery, War",74217,8.62
...,...,...,...,...,...,...,...,...
593,Ferris Bueller's Day Off,1986,103 min,U,7.8,Comedy,358202,70.14
594,I Love You Phillip Morris,2009,102 min,R,6.6,"Biography, Comedy, Crime",96420,2.04
597,Choke,2008,92 min,R,6.4,"Comedy, Drama",32753,2.93
598,The Conjuring,2013,112 min,A,7.5,"Horror, Mystery, Thriller",507280,137.40
599,Body Heat,1981,113 min,18,7.4,"Crime, Drama, Romance",36182,24.06

In [33]:
movie['Run Time'] = movie['Run Time'].apply(lambda x:x.replace(' min',''))

In [34]:
movie

,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross in M $
0,The Godfather,1972,175,A,9.2,"Crime, Drama",408693,435.11
1,Goodfellas,1990,145,A,8.7,"Biography, Crime, Drama",31290,13.56
2,Pulp Fiction,1994,154,A,8.9,"Crime, Drama",788510,380.26
3,The Usual Suspects,1995,106,A,8.5,"Crime, Drama, Mystery",179202,11.50
4,Apocalypse Now,1979,147,R,8.5,"Drama, Mystery, War",74217,8.62
...,...,...,...,...,...,...,...,...
593,Ferris Bueller's Day Off,1986,103,U,7.8,Comedy,358202,70.14
594,I Love You Phillip Morris,2009,102,R,6.6,"Biography, Comedy, Crime",96420,2.04
597,Choke,2008,92,R,6.4,"Comedy, Drama",32753,2.93
598,The Conjuring,2013,112,A,7.5,"Horror, Mystery, Thriller",507280,137.40
599,Body Heat,1981,113,18,7.4,"Crime, Drama, Romance",36182,24.06

In [35]:
movie.dtypes

Movie Name       object
Year             object
Run Time         object
Certificate      object
Rating          float64
Genre            object
Votes            object
Gross in M $     object
dtype: object

In [36]:
movie['Rating']=movie['Rating'].astype('float')
movie['Votes']=movie['Votes'].astype('int')
movie['Run Time']=movie['Run Time'].astype('int')
movie['Gross in M $']=movie['Gross in M $'].astype('float')

In [37]:
movie['Year'].value_counts()

2002    24
1999    23
2010    19
2004    19
2005    19
        ..
2017     1
1956     1
1942     1
1958     1
1940     1
Name: Year, Length: 72, dtype: int64

In [38]:
movie['Year'] = movie['Year'].apply(lambda x:x.replace('  ',''))

In [39]:
movie['Year'] = movie['Year'].apply(lambda x:x.replace(' '' ',''))

In [40]:
movie['Year'][0]

'1972'

In [41]:
movie['Year'].unique()

array(['1972', '1990', '1994', '1995', '1979', '1996', '1999', '1993',
       '1997', '1992', '1975', '1976', '1985', '1974', '1983', '2001',
       '1986', '1998', '1980', '2009', '2006', '2002', '1984', '1973',
       '2000', '1981', '1988', '1942', '2010', '1987', '2005', '1971',
       'I ', '1982', '1941', '2004', '2003', '1991', '1989', '1957',
       '1964', '2007', '1946', '1977', '1966', '2013', '1978', '1969',
       '1967', '1939', '2008', '1954', '1968', '1960', '2011', '2018',
       '500 Days of Summer', '2019', '1962', '2012', '1961', '2014',
       '2015', '2016', '1949', '1959', '1970', '2017', '1956', '1963',
       '1958', '1940'], dtype=object)

In [56]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie Name    542 non-null    object
 1   Year          542 non-null    object
 2   Run Time      542 non-null    int32
 3   Certificate   542 non-null    object
 4   Rating        542 non-null    float64
 5   Genre         542 non-null    object
 6   Votes         542 non-null    int32
 7   Gross in M $  542 non-null    float64
dtypes: float64(2), int32(2), object(4)
memory usage: 29.8+ KB

# We have 542 rows but in data frame it is showing 600,So we will reset the index

In [57]:
movie.reset_index(inplace=True)
movie

,index,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross in M $
0,0,The Godfather,1972,175,A,9.2,"Crime, Drama",408693,435.11
1,1,Goodfellas,1990,145,A,8.7,"Biography, Crime, Drama",31290,13.56
2,2,Pulp Fiction,1994,154,A,8.9,"Crime, Drama",788510,380.26
3,3,The Usual Suspects,1995,106,A,8.5,"Crime, Drama, Mystery",179202,11.50
4,4,Apocalypse Now,1979,147,R,8.5,"Drama, Mystery, War",74217,8.62
...,...,...,...,...,...,...,...,...,...
537,537,Ferris Bueller's Day Off,1986,103,U,7.8,Comedy,358202,70.14
538,538,I Love You Phillip Morris,2009,102,R,6.6,"Biography, Comedy, Crime",96420,2.04
539,539,Choke,2008,92,R,6.4,"Comedy, Drama",32753,2.93
540,540,The Conjuring,2013,112,A,7.5,"Horror, Mystery, Thriller",507280,137.40
541,541,Body Heat,1981,113,18,7.4,"Crime, Drama, Romance",36182,24.06

In [58]:
movie.drop('index',axis=1,inplace=True)

In [59]:
movie

,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross in M $
0,The Godfather,1972,175,A,9.2,"Crime, Drama",408693,435.11
1,Goodfellas,1990,145,A,8.7,"Biography, Crime, Drama",31290,13.56
2,Pulp Fiction,1994,154,A,8.9,"Crime, Drama",788510,380.26
3,The Usual Suspects,1995,106,A,8.5,"Crime, Drama, Mystery",179202,11.50
4,Apocalypse Now,1979,147,R,8.5,"Drama, Mystery, War",74217,8.62
...,...,...,...,...,...,...,...,...
537,Ferris Bueller's Day Off,1986,103,U,7.8,Comedy,358202,70.14
538,I Love You Phillip Morris,2009,102,R,6.6,"Biography, Comedy, Crime",96420,2.04
539,Choke,2008,92,R,6.4,"Comedy, Drama",32753,2.93
540,The Conjuring,2013,112,A,7.5,"Horror, Mystery, Thriller",507280,137.40
541,Body Heat,1981,113,18,7.4,"Crime, Drama, Romance",36182,24.06

# Checking for NaN values

In [60]:
movie.isna().sum()

Movie Name      0
Year            0
Run Time        0
Certificate     0
Rating          0
Genre           0
Votes           0
Gross in M $    0
dtype: int64

# Getting error while converting

In [71]:
movie['Year'].unique()

array([1972, 1990, 1994, 1995, 1979, 1996, 1999, 1993, 1997, 1992, 1975,
       1976, 1985, 1974, 1983, 2001, 1986, 1998, 1980, 2009, 2006, 2002,
       1984, 1973, 2000, 1981, 1988, 1942, 2010, 1987, 2005, 1971, 1982,
       1941, 2004, 2003, 1991, 1989, 1957, 1964, 2007, 1946, 1977, 1966,
       2013, 1978, 1969, 1967, 1939, 2008, 1954, 1968, 1960, 2011, 2018,
       2019, 1962, 2012, 1961, 2014, 2015, 2016, 1949, 1959, 1970, 2017,
       1956, 1963, 1958, 1940])

## Here i found that there are some string values in Year column

In [72]:
movie = movie[movie['Year']!='500 Days of Summer']

In [73]:
movie['Year']= movie['Year'].astype(int)

In [74]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 530 entries, 0 to 541
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Movie Name    530 non-null    object
 1   Year          530 non-null    int32
 2   Run Time      530 non-null    int32
 3   Certificate   530 non-null    object
 4   Rating        530 non-null    float64
 5   Genre         530 non-null    object
 6   Votes         530 non-null    int32
 7   Gross in M $  530 non-null    float64
dtypes: float64(2), int32(3), object(3)
memory usage: 31.1+ KB

In [75]:
movie.head()

,Movie Name,Year,Run Time,Certificate,Rating,Genre,Votes,Gross in M $
0,The Godfather,1972,175,A,9.2,"Crime, Drama",408693,435.11
1,Goodfellas,1990,145,A,8.7,"Biography, Crime, Drama",31290,13.56
2,Pulp Fiction,1994,154,A,8.9,"Crime, Drama",788510,380.26
3,The Usual Suspects,1995,106,A,8.5,"Crime, Drama, Mystery",179202,11.50
4,Apocalypse Now,1979,147,R,8.5,"Drama, Mystery, War",74217,8.62

In [76]:
movie.to_csv(r'C:\Users\NaveenNani\OneDrive\Desktop\Desktop\Cleaned_Data_Imdb.csv')

In [77]:
# Cleaning is done
# Now we can visualise the data